#:schema node_modules/wrangler/config-schema.json
name = "api"
main = "src/main.ts"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "api"
[env.production.vars]
ALLOW_ORIGIN = "https://hrkmtsmt.me"
QIITA_API_URL = "https://qiita.com/api/v2"
QIITA_BASE_URL = "https://qiita.com"
SIZU_API_URL = "https://sizu.me/api"
SIZU_BASE_URL = "https://sizu.me"
ZENN_API_URL = "https://zenn.dev/api"
ZENN_BASE_URL = "https://zenn.dev"

[triggers]
crons = ["0 0 * * mon"]

[[env.production.d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "hrkmtsmt"
database_id = "51791b72-d7cb-442e-827e-2b7f69919939"
migrations_dir = "migrations"
